# Generated by Django 5.1.7 on 2025-03-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_app', '0002_car_seller_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='For Sale', max_length=200),
        ),
    ]
